RPOS UI/ResturantPOS/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ResturantPOS.Models
{
    public class Category
    {
        public int Cat_ID { get; set; }
        public string CategoryName { get; set; }
        public decimal ST { get; set; }
        public decimal VAT { get; set; }
        public decimal SC { get; set; }
        public String BkColor { get; set; }
    }
}

RPOS UI/ResturantPOS/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web; 

namespace ResturantPOS.Models
{
    public class Expense
    {
        public string ExpenseName { get; set; }
        public string ExpenseType { get; set; }
    }
}

RPOS UI/ResturantPOS/Controllers/BackOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResturantPOS.Controllers
{
    public class BackOfficeController : Controller
    {
        // GET: BackOffice
        public ActionResult BackOffice()
        {
            return View();
        }
    }
}

RPOS UI/ResturantPOS/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ResturantPOS.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace ResturantPOS.Controllers
{
    public class ExpenseController : Controller
    {
        // GET: Expense

        string Baseurl = "http://localhost:2159/";
        public async Task<ActionResult> ExpenseList()


        {
            List<Expense> Expense1 = new List<Expense>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage Res = await client.GetAsync("api/Expense");


                if (Res.IsSuccessStatusCode)
                {

                    var Curr = Res.Content.ReadAsStringAsync().Result;


                    Expense1 = JsonConvert.DeserializeObject<List<Expense>>(Curr);

                }
            }
            List<ExpenseTypecs> ExpenseTypecs = new List<ExpenseTypecs>();

            using (var client1 = new HttpClient())
            {
                client1.BaseAddress = new Uri(Baseurl);

                client1.DefaultRequestHeaders.Clear();

                client1.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage Res1 = await client1.GetAsync("api/ExpensType");


                if (Res1.IsSuccessStatusCode)
                {

                    var Curr = Res1.Content.ReadAsStringAsync().Result;


                    ExpenseTypecs = JsonConvert.DeserializeObject<List<ExpenseTypecs>>(Curr);

                }

                List<SelectListItem> Items = new List<SelectListItem>();
                foreach (var c in ExpenseTypecs)
                {
                    Items.Add(new SelectListItem
                    {
                        Text = c.Type,
                        Value = c.Type
                    });
                }

                ViewBag.Type = Items;
                Session["UserModel"] = Expense1;
                return PartialView(Expense1);
            }
        }





        public ActionResult SaveExpense(string ExpenseName1, string ExpenseName2, string ExpenseType)
        {

            Expense Exp = new Expense();
            string ExpenseName = ExpenseName1;
            Exp.ExpenseName = ExpenseName2;
            Exp.ExpenseType = ExpenseType;

            using (var client2 = new HttpClient())
            {
                //Passing service base url  
                client2.BaseAddress = new Uri(Baseurl);
                client2.DefaultRequestHeaders.Clear();
                //Define request data format  
                client2.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = client2.PutAsJsonAsync("api/Expense/" + ExpenseName, Exp).Result;
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var CatResponse = Res.Content.ReadAsStringAsync().Result;
                    ViewBag.Name = JsonConvert.SerializeObject(CatResponse);
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    //CatInfo = JsonConvert.DeserializeObject<List<Category>>(CatResponse);
                }
                return RedirectToAction("ExpenseList");
            }
        }
        public ActionResult DeleteExpense(Expense Exp)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = client.DeleteAsync("api/Expense/" + Exp.ExpenseName).Result;
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var CatResponse = Res.Content.ReadAsStringAsync().Result;
                    ViewBag.Name = JsonConvert.SerializeObject(CatResponse);
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    //CatInfo = JsonConvert.DeserializeObject<List<Category>>(CatResponse);
                }
            }
            return RedirectToAction("ExpenseList");
        }



        public ActionResult SaveCategory(Expense Exp)
        {
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = client.PostAsJsonAsync("api/Expense", Exp).Result;
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var CatResponse = Res.Content.ReadAsStringAsync().Result;
                    ViewBag.Name = JsonConvert.SerializeObject(CatResponse);
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    //CatInfo = JsonConvert.DeserializeObject<List<Category>>(CatResponse);
                }
                return RedirectToAction("ExpenseList");
            }
        }
    }
}

    

RPOS UI/ResturantPOS/Controllers/ResturantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using ResturantPOS.Models;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace ResturantPOS.Controllers
{
    public class ResturantController : Controller
    {
        string Baseurl = "http://localhost:2159/";
        // GET: Resturant
        public ActionResult BackOffice()
        { 
            return View();
        }

        public ActionResult ResturantInfo()
        {
            return View();
        }
        public ActionResult CurrencyRate()
        {
            return View();
        }
        public ActionResult Category()
        {
            return View();
        }

        public ActionResult SectionInfo()
        {
            return View();
        }

        public ActionResult MenuItems()
        {
            return View();
        }

        public async Task<ActionResult> MenuItemsStock()
    {
            List<Stock_Store> Dish = new List<Stock_Store>();
            List<Stock_Store_myjoin> mydata = new List<Stock_Store_myjoin>();
            Stock_Store model1 = new Stock_Store();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage Res = await client.GetAsync("api/Stock_Store");


                if (Res.IsSuccessStatusCode)
                {

                    var Curr = Res.Content.ReadAsStringAsync().Result;
                    Dish = JsonConvert.DeserializeObject<List<Stock_Store>>(Curr);
       

                }
   
                model1.St_ID = Dish.Select(s => s.St_ID).LastOrDefault();
                model1.Date= Dish.Select(s => s.Date).LastOrDefault();
                model1.Remarks= Dish.Select(s => s.Remarks).LastOrDefault();
            }
           // List<Category> Category = new List<Category>();

            using (var client1 = new HttpClient())
            {
                client1.BaseAddress = new Uri(Baseurl);

                client1.DefaultRequestHeaders.Clear();

                client1.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage Res1 = await client1.GetAsync("api/Stock_Store_Join");


                if (Res1.IsSuccessStatusCode)
                {

                    var Curr = Res1.Content.ReadAsStringAsync().Result;


                    mydata = JsonConvert.DeserializeObject<List<Stock_Store_myjoin>>(Curr);

                }
                //model.Sid = Category.Select(s => s.Cat_Id).LastOrDefault();
                List<SelectListItem> Items = new List<SelectListItem>();
                foreach (var c in mydata)
                {
                    Items.Add(new SelectListItem
                    {
                         Value = c.Dish,
                         Text = c.Dish
                    });
                }
               ViewBag.mydata= Items;


            }

            List<Kitchen> Kitchen = new List<Kitchen>();

            using (var client2 = new HttpClient())
            {
                client2.BaseAddress = new Uri(Baseurl);

                client2.DefaultRequestHeaders.Clear();

                client2.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage Res2 = await client2.GetAsync("api/Kitchen");


                if (Res2.IsSuccessStatusCode)
                {

                    var Curr1 = Res2.Content.ReadAsStringAsync().Result;


                    Kitchen = JsonConvert.DeserializeObject<List<Kitchen>>(Curr1);

                }

                List<SelectListItem> Items2 = new List<SelectListItem>();
                //foreach (var c in Kitchen)
                //{
                //    model1.Getdashdata.Add(new Stock_Store
                //    {
                //         StockId = c.,
                //        Dish = c.Kitchenname
                //    });
                //}

                ViewBag.Kichen = Items2;
                Session["UserModel"] = Dish;
                return View(model1);



            }


        }

        [HttpPost]
       public ActionResult MenuItemsStock(string Sname, int Iqty)
        {


            Stock_Store_myjoin model = new Stock_Store_myjoin();
            
                model.Dish = Sname;
            model.Qty = Iqty;
            model.StockID =4;
            using (
                var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = client.PostAsJsonAsync("api/Stock_Store_Join", model).Result;
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var CatResponse = Res.Content.ReadAsStringAsync().Result;
                    ViewBag.Name = JsonConvert.SerializeObject(CatResponse);
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    //CatInfo = JsonConvert.DeserializeObject<List<Category>>(CatResponse);
                    return RedirectToAction("MenuItemsStock");
                }

                return View();
            }
        }
        public ActionResult Table()
        {
            return View();
        }
        public ActionResult Settings()
        {

            return View();
        }
        public ActionResult POSPrinterSetting()
        {

            return View();
        }
        public ActionResult EmailSetting()
        {

            return View();
        }
        public ActionResult SMSSettings()
        {

            return View();
        }
        public ActionResult OtherSettings()
        {

            return View();
        }
        public ActionResult Database()
        {
            return View();
        }
        public ActionResult Note()
        {
            return View();
        }

        public ActionResult Hotel()
        {
            return View();
        }
        public ActionResult Wallet()
        {
            return View();
        }
        public ActionResult RPOSCard()
        {
            return View();
        }
        public ActionResult AddMember()
        {
            return View();
        }
        public ActionResult AddFunds()
        {
            return View();
        }
        public ActionResult Refund()
        {
            return View();
        }
        public ActionResult PrintCards()
        {
            return View();
        }
        public ActionResult MemberLedger()
        {
            return View();
        }
        public ActionResult WareHouseType()
        {
            return View();
        }
        public ActionResult WareHouse()
        {
            return View();
        }
        public ActionResult Supplier()
        {
            return View();
        }
        public ActionResult ExpenseType()
        {
            return View();
        }
        public ActionResult Expense()
        {
            return View();
        }
        public ActionResult Voucher()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }

        public ActionResult AccountingReports()
        {
            return View();
        }
        public ActionResult WorkPeriod()
        {
            return View();
        }
        public ActionResult Registration()
        {
            return View();
        }
        public ActionResult Logs()
        {
            return View();
        }
        public ActionResult POSReport()
        {
            return View();
        }
        public ActionResult ChangePIN()
        {
            return View();
        }
        public ActionResult Recipe()
        {
            return View();
        }
        public ActionResult Delivery()
        {
            return View();
        }
        public ActionResult DeliveryPerson()
        {
            return View();
        }
        public ActionResult OtherResource()
        {
            return View();
        }
        public ActionResult StockIssues()
        {
            return View();
        }
        public ActionResult Payment()
        {
            return View();
        }
        public ActionResult RawMaterials()
        {
            return View();
        }
        public ActionResult Listofsuppliers()
        {
            return View();
        }


        public ActionResult PurchaseEntry()
        {
            return View();
        }





    }
    }

RPOS UI/ResturantPOS/Views/Resturant/About.cshtml

@{
    ViewBag.Title = "About";
}

<h2>About Us</h2>

<head>
    <link href="~/Content/About.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-12 col-xs-12">
                <img src="https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAh5AAAAJDY0NTU0MzRiLTA5YmYtNGZjYS1iZGI2LThkYzViZDQyNzQ4MA.jpg" class="about-image">
            </div>

            <div class="col-md-8 col-sm-12 col-xs-12 about-content">
                <div class="form-group">
                    <label class="form-text-label">Restaurant POS</label>
                </div>
                <div class="form-group">
                    <label class="form-text-label">Version 4.2.1.0 </label>
                </div>
                <div class="form-group">
                    <label class="form-text-label">Copyright @DateTime.Now.Year </label>
                </div>
                <div class="form-group">
                    <label class="form-text-label">Developed By: CARAMEL IT SERVICES pvt.ltd </label>
                </div>
                <div class="form-group">
                    <label><p>Warning: Please do not distribute this computer program without permission of its owner. Unauthorized reproduction or distrubution of this program or any portion of it, may result in severe civil and criminal penalities</p></label>
                </div>
            </div>



        </div>
    </div>
</body>

RPOS UI/ResturantPOS/Views/Resturant/AddMember.cshtml

@{
    ViewBag.Title = "AddMember";
}

<h2 style="text-align:center">Member Registration</h2>

<link href="~/Content/AddMember.css" rel="stylesheet" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container ">
    <div class="row member">
        
        <div class="col-md-3" id="btnn">
            
        </div>

        <!-- text boxs to enter the information-->
        <div class="col-md-6">
            <div class="form-text">
                <label class="form-text-label">Member ID : </label> <input type="text" class="label-text-box">
            </div>

            <div class="form-text">
                <label class="form-text-label">Member Name : </label> <input type="text" class="label-text-box">
            </div>

            <div class="form-text">
                <label class="form-text-label">Address : </label> <input type="text" class="label-text-box">
            </div>

            <div class="form-text">
                <label class="form-text-label">Contact Number : </label> <input type="text" class="label-text-box">
            </div>

            <div class="form-text">
                <label class="form-text-label">Status : </label> <input type="checkbox" class="label-check-box"> <label class="form-text-lbl">Is Active</label> 
            </div>
            <div class="form-group" style="width: 246%;">
                <label for="inputtext3" class="col-sm-2 control-label">Search By Member Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputtext3">
                </div>
            </div>
        </div>

        <!-- new save edit and delete buttons-->
        <div class="col-md-3" id="controls">
           
            <button id="controls-inner"><i class="fa fa-refresh fa-2x" aria-hidden="true"></i><strong class="txt">Reset</strong></button>
            <button id="controls-inner"><i class="fa fa-file-excel-o fa-2x" aria-hidden="true"></i><strong class="txt">Export Excel</strong></button>
            
        </div>
    </div>
</div>

RPOS UI/ResturantPOS/Views/Resturant/BackOffice.cshtml

@{
    ViewBag.Title = "BackOffice";
}



    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Hotel","Hotel")'"><i class="fa fa-university fa-3x" aria-hidden="true"></i><br /> <h4>Restaurant Info </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("CurrencyRate","Currency")'"><i class="fa fa-money fa-3x" aria-hidden="true"></i> <br /><h4>Currency Rate</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Category","Home")'"><i class="fa fa-delicious fa-3x" aria-hidden="true"></i> <br /><h4>Categories</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Kitchen","Kitchen")'"><i class="fa fa-simplybuilt fa-3x" aria-hidden="true"></i> <br /><h4>Kitchen/Section</h4></button>
        </div>
    </div>


    <!--1st row end-->


    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("MenuItems","MenuItems")'"><i class="fa fa-bars fa-3x" aria-hidden="true"></i><br /> <h4>Menu </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("MenuStock", "MenuStock")'"><i class="fa fa-tachometer fa-3x" aria-hidden="true"></i> <br /><h4>Menu Items Stock</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("R_Table","R_Table")'"><i class="fa fa-table fa-3x" aria-hidden="true"></i> <br /><h4>Tables</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("NotesMaster", "NotesMaster")'"><i class="fa fa-clipboard fa-3x" aria-hidden="true"></i> <br /><h4>Notes</h4></button>
        </div>
    </div>


    <!--2nd row end-->


    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Settings","Resturant")'"><i class="fa fa-cog fa-3x" aria-hidden="true"></i> <br /> <h4>Settings </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Database","Resturant")'"><i class="fa fa-database fa-3x" aria-hidden="true"></i> <br /><h4>Database</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Wallet","Wallet")'"><i class="fa fa-google-wallet fa-3x" aria-hidden="true"></i> <br /><h4>Wallet</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("RPOSCard","Resturant")'"><i class="fa fa-id-badge fa-3x" aria-hidden="true"></i> <br /><h4>RPOS Cards</h4></button>
        </div>
    </div>



    <!--3rd row end-->

    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("WareHouseType","Type")'"><i class="fa fa-briefcase fa-3x" aria-hidden="true"></i><br /> <h4>Warehouse Type </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("WareHouse","WareHouse")'"><i class="fa fa-home fa-3x" aria-hidden="true"></i> <br /><h4>Warehouse</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Product_OpeningStock", "Product_OpeningStock")'"><i class="fa fa-cart-arrow-down fa-3x" aria-hidden="true"></i> <br /><h4>Raw Materials</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Supplier","Supplier")'"><i class="fa fa-address-card fa-3x" aria-hidden="true"></i> <br /><h4>Supplier</h4></button>
        </div>
    </div>



    <!--4the row end-->


    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("PurchaseEntry","Resturant")'"><i class="fa fa-balance-scale fa-3x" aria-hidden="true"></i> <br /> <h4>Purchase </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Payment","Resturant")'"><i class="fa fa-handshake-o fa-3x" aria-hidden="true"></i> <br /><h4>Payment</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("StockTransfer_Join", "StockTransfer_Join")'"><i class="fa fa-truck fa-3x" aria-hidden="true"></i> <br /><h4>Stock Transfer</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("ExpenseType","ExpenseType")'"><i class="fa fa-dropbox fa-3x" aria-hidden="true"></i><br /><h4>Expense Type</h4></button>
        </div>
    </div>


    <!--5th row end-->


    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("ExpenseList","Expense")'"><i class="fa fa-inr fa-3x" aria-hidden="true"></i> <br /> <h4>Expense </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Voucher","Resturant")'"><i class="fa fa-file-text-o fa-3x" aria-hidden="true"></i> <br /><h4>Voucher</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Delivery","Resturant")'"><i class="fa fa-male fa-3x" aria-hidden="true"></i><br /><h4>Delivery Person</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("WorkPeriod","Resturant")'"><i class="fa fa-calendar fa-3x" aria-hidden="true"></i> <br /><h4>Work Period</h4></button>
        </div>
    </div>


    <!--6th row end-->



    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Recipe","Resturant")'"><i class="fa fa-book fa-3x" aria-hidden="true"></i> <br /> <h4>Recipe </h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("POSReport","Resturant")'"><i class="fa fa-money fa-3x" aria-hidden="true"></i> <br /><h4>POS Report</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("WorkPeriod","Resturant")'"><i class="fa fa-calendar-check-o fa-3x" aria-hidden="true"></i> <br /><h4>Work Period Report</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("AccountingReports","Resturant")'"><i class="fa fa-pie-chart fa-3x" aria-hidden="true"></i> <br /><h4>Accounting Reports</h4></button>
        </div>
    </div>


    <!--7th row end-->


    <div class="row">
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Registration","Registration")'"><i class="fa fa-user-plus fa-3x" aria-hidden="true"></i> <br /> <h4>Registration</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("ChangePIN","Resturant")'"><i class="fa fa-key fa-3x" aria-hidden="true"></i> <br /><h4>Change Pin</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("Logs","Resturant")'"><i class="fa fa-linode fa-3x" aria-hidden="true"></i> <br /><h4>Logs</h4></button>
        </div>
        <div class="col-md-3 col-xs-6" id="btnn">
            <button id="btnn-inner" onclick="location.href='@Url.Action("About","Resturant")'"><i class="fa fa-user fa-3x" aria-hidden="true"></i> <br /><h4>About</h4></button>
        </div>
    </div>


    <!--8th row end-->